package top.craft_hello.tpa.enums;

public enum RequestType {
    TPA, TPHERE, TPALL, TPLOGOUT, TPACCEPT, TPDENY, DENYS, WARP, SETWARP, DELWARP, HOME, HOMES, SETHOME, SETDEFAULTHOME, DELHOME, SPAWN, SETSPAWN, DELSPAWN, BACK, RELOAD, SETLANG, VERSION
}
